#!/bin/bash
set -e
echo "Importando o prisma para /lib/prisma-imported"
bun i @prisma/client prisma
bunx prisma generate
cp -r node_modules/@prisma/client src/lib/prisma-imported/@prisma
cp -r node_modules/.prisma src/lib/prisma-imported/.prisma
echo "Prisma importado com sucesso"
echo "Removendo o prisma do node_modules"
rm -rf node_modules/@prisma node_modules/.prisma
echo "Prisma removido com sucesso"